services:

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network
    develop: # This is for development purposes it allows for hot-reloading and syncing changes without rebuilding the image.
      watch:
      - action: sync
        path: ./Frontend
        target: /app
      - action: rebuild
        path: ./Frontend/package.json


  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=postgresql://SousChef:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - RESEND_API_KEY=${RESEND_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    develop: # Same for this one it allows for hot-reloading and syncing changes without rebuilding the image.
      watch:
        - action: sync
          path: ./Backend
          target: /app
        - action: rebuild
          path: ./Backend/package.json
    env_file: # for the Gemini Live API Key
      - .env 



  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network


volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
